 <?php 
        session_start();
        if(!isset($_SESSION['email'])){
            header('Location:index.html');
        }
        $name=$_SESSION['name'];
        $img=$_SESSION['img'];
        $email=$_SESSION['email'];
    ?>